# (question, page, persona). Personas: a lead new build, b older house, c member, d small business, e growth or ops, f block host.
QUESTIONS = [
    ("Where did Base Power pull the most permits last month? Give the top zip codes.", "market", "e"),
    ("How many Auxiliary Power (backup) permits were issued citywide in February 2021 versus February 2022?", "recovery", "e"),
    ("How many permits has Base Power pulled in each month of 2026?", "market", "e"),
    ("How many Base Power permits were issued in the last 30 days, by status?", "admin", "e"),
    ("How many Auxiliary Power permits were issued in Austin each year from 2019 to 2026?", "story", "e"),
    ("How many Base Power permits were issued in zip 78731 this year?", "star", "e"),
    ("How many backup permits were issued in zip 78745 in 2025?", "house", "b"),
    ("How many solar permits were issued in Austin each month of 2026?", "grid", "c"),
    ("Which zip codes had the most solar permits in 2025?", "placement", "f"),
    ("How many backup battery permits were issued in August 2026?", "index", "e"),
    ("Which zip codes had the most backup permits last month?", "explorer", "e"),
    ("How many Base Power permits were issued in July 2026 versus August 2026?", "market", "e"),
    ("How many Base Power permits are still active in zip 78757?", "member", "c"),
    ("How many solar permits were issued in zip 78704 in 2026?", "block", "f"),
    ("Which contractors pulled the most Auxiliary Power permits in 2026, and how does Base compare?", "market", "e"),
    ("What share of Base Power permits are final versus still active?", "admin", "e"),
    ("What is the median number of days from application to issue for Base Power permits?", "journey", "a"),
    ("Which zips have the most Base permits per 1,000 owner-occupied homes?", "star", "e"),
    ("Which zip codes have solar permits but no battery permits?", "placement", "f"),
    ("How many backup permits were issued each month of 2023?", "recovery", "e"),
    ("How many hours in 2026 had a day-ahead price over $1,000 per MWh on LZ_AEN?", "grid", "c"),
    ("What was the highest LZ_AEN day-ahead price in 2025 and on which date and hour?", "grid", "c"),
    ("What is the average LZ_AEN day-ahead price by month in 2026?", "member", "c"),
    ("How many hours in 2025 was the LZ_AEN day-ahead price below zero?", "tower", "c"),
    ("How many hours in 2025 was the LZ_NORTH price over $100?", "grid", "d"),
    ("What were the top 5 LZ_AEN price days in 2025?", "tower", "c"),
    ("What were the top price days on LZ_HOUSTON in 2026?", "demo", "d"),
    ("How many hours in August 2025 had an LZ_AEN price over $200?", "member", "c"),
    ("How many hours in 2026 was the Houston zone price over $500?", "grid", "d"),
    ("How many hours in 2026 was the LZ_AEN price negative?", "block", "f"),
    ("What was the highest LZ_NORTH day-ahead price in 2026?", "judgments", "e"),
    ("What is the average LZ_HOUSTON price by month in 2025?", "tower", "d"),
    ("At what hour of the day does ERCOT system load peak on average in 2025?", "grid", "f"),
    ("What was the highest hourly ERCOT load in 2024, 2025 and 2026?", "tower", "f"),
    ("Which month of 2025 had the highest peak South Central (SCENT) load?", "block", "f"),
    ("What was the peak South Central load in 2026?", "block", "f"),
    ("At what hour does South Central load peak on average in 2026?", "placement", "f"),
    ("Which month of 2024 had the highest ERCOT peak load?", "grid", "e"),
    ("What was the peak Coast zone load in 2025?", "tower", "d"),
    ("Which storm months drove backup permit surges?", "recovery", "e"),
    ("Which months had more than 4 times the 2020 backup permit rate?", "recovery", "e"),
    ("How long did the backup permit surge after Winter Storm Uri last?", "story", "b"),
    ("What was the peak month for backup permits after the 2023 ice storm?", "recovery", "b"),
    ("Which zip codes have the most easy-fit homes?", "star", "a"),
    ("How many easy-fit homes are in zip 78665?", "journey", "a"),
    ("How many easy-fit homes are in zip 78745?", "house", "a"),
    ("How many easy-fit homes are in zip 78664?", "star", "a"),
    ("What share of houses in the 78745 cohort are easy fits?", "wall", "a"),
    ("Who sells power in zip 78665?", "journey", "a"),
    ("Which utility serves zip 78704?", "house", "b"),
    ("Which zip codes have zero retail electricity plans on Power to Choose (no retail choice)?", "gaps", "d"),
    ("How many retail plans are available in zip 78626?", "member", "d"),
    ("Which zips are served by Oncor?", "star", "e"),
    ("Which zip codes rank highest for assisted onboarding priority?", "voice", "b"),
    ("What is the assisted priority score for zip 76574?", "voice", "b"),
    ("Which zips have the highest share of people 65 or older?", "voice", "b"),
    ("Which zip codes have the highest deed turnover in the last 2 years?", "placement", "e"),
    ("What share of homes in zip 78745 sold in the last 2 years according to deeds?", "house", "b"),
    ("Which zips have the most homes held 20 years or more?", "house", "b"),
    ("What is the median years since last deed in zip 78731?", "star", "a"),
    ("Which Austin-area zip codes have the most owner-occupied homes?", "star", "e"),
    ("Which zip codes have a median home value over $600,000 and how many households do they have?", "placement", "e"),
    ("What is the median year built of homes in zip 78745?", "house", "b"),
    ("What is the median household income in zip 78731?", "journey", "a"),
    ("Which zip codes have the oldest housing stock?", "wall", "b"),
    ("How many households are in zip 78665?", "explorer", "a"),
    ("Which zip codes had more solar permits than battery permits from 2016 to 2026?", "placement", "f"),
    ("How many service upgrade permits were issued in zip 78745 from 2016 to 2026?", "house", "b"),
    ("What is the average LZ_AEN price in hour ending 19 during August 2025?", "member", "c"),
    ("How much higher was the LZ_HOUSTON price than LZ_AEN on average in 2025?", "grid", "d"),
    ("What was the average ERCOT load in July 2025?", "tower", "f"),
    ("How many new single family home permits were issued in zip 78660 from 2016 to 2026?", "placement", "a"),
    ("Which Base zips have a final rate above 20 percent?", "market", "e"),
    ("What share of Auxiliary Power permits in 2026 went to Base Power?", "market", "e"),
    ("How many hours in summer 2025, June to August, had LZ_AEN prices over $100?", "member", "c"),
    ("Which weather zone had the highest peak load in 2025?", "grid", "f"),
    ("How many easy-fit homes are there in Williamson County zips?", "star", "e"),
    ("Which zips have HIGH confidence and more than 5,000 easy-fit homes?", "placement", "e"),
    ("How many Base Power permits were issued in the 30 days after the Backup Only launch on 2026-07-15?", "story", "e"),
    ("Which zips have more than 20,000 households and a median income over $100,000?", "demo", "d"),
]
